apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minecraft
  namespace: minecraft
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    acme.kubernetes.io/enable: "true"
    acme.kubernetes.io/dns: "dns_cf"
spec:
  rules:
    - host: minecraft.ttys0.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: amber
                port:
                  number: 8123
  tls:
    - hosts:
        - minecraft.ttys0.net
      secretName: minecraftttys0net-tls
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minecraft-ext
  namespace: minecraft
  annotations:
    kubernetes.io/ingress.class: nginx-external
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  rules:
    - host: minecraft.ttys0.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: amber
                port:
                  number: 8123
  tls:
    - hosts:
        - minecraft.ttys0.net
      secretName: minecraftttys0net-tls
